# Spring properties
spring:
    application:
        name: AUTH-SERVICE

# Discovery Server Access
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true

# HTTP Server
server:
    port: 0