server:
  port: 8383

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
  instance:
    preferIpAddress: true
    hostname: eureka-0

spring:
  application:
    name: SHIPPING-SERVICE
