server:
  port: 9292

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      database: ${}
      host: ${}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
  instance:
    preferIpAddress: true
    hostname: eureka-0