apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service-app
  labels:
    app: accounts-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-service-app
  template:
    metadata:
      labels:
        app: accounts-service-app
    spec:
      containers:
      - name: accounts-service-app
        image: djff94/account-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "0.2"
        ports:
          - containerPort: 8282
        env:
          - name: SPRING_DATASOURCE_PASSWORD
            value: root
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://account-service-mysql-db:3306/testdb?createDatabaseIfNotExist=true&useSSL=false
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_JPA_HIBERNATE_DDL-AUTO
            value: update
          - name: EUREKA_URI
            value: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: accounts-service-svc
spec:
  selector:
    app: accounts-service-app
  ports:
  - port: 80
    targetPort: 8282

