apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-app
  labels:
    app: config-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-service-app
  template:
    metadata:
      labels:
        app: config-service-app
    spec:
      containers:
      - name: config-service-app
        image: djff94/config-server:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
          - containerPort: 9296
        env:
          - name: EUREKA_URI
            value: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: config-service-svc
spec:
  selector:
    app: config-service-app
  ports:
  - port: 80
    targetPort: 9296

