# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: eureka-server-
# data:
#   eureka_service_address: http://eureka-0.eureka:8761/eureka
# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-app
  labels:
    app: gateway-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service-app
  template:
    metadata:
      labels:
        app: gateway-service-app
    spec:
      containers:
      - name: gateway-service-app
        image: djff94/gateway-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.2"
        ports:
          - containerPort: 9191
        env:
          - name: S2S_LOCAL_TOKEN
            value: YXBpLXNlcnZpY2UtYWNjb3VudDpwd2QkMjAyMQ==
          - name: EUREKA_URI
            value: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service-svc
spec:
  selector:
    app: gateway-service-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9191
    protocol: TCP

