apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-app
  labels:
    app: gateway-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-app
  template:
    metadata:
      labels:
        app: gateway-service-app
    spec:
      containers:
      - name: gateway-service-app
        image: djff94/gateway-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
          - containerPort: 9191

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service-svc
spec:
  selector:
    app: gateway-service-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9191
    protocol: TCP

