apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service-app
  labels:
    app: orders-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service-app
  template:
    metadata:
      labels:
        app: orders-service-app
    spec:
      containers:
      - name: orders-service-app
        image: djff94/order-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
          - containerPort: 9292
        env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://account-service-mysql-db:3306/testdb?createDatabaseIfNotExist=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_JPA_HIBERNATE_DDL-AUTO
              value: update
            - name: EUREKA_URI
              value: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: orders-service-svc
spec:
  selector:
    app: orders-service-app
  ports:
  - port: 80
    targetPort: 9292

