apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-app
  labels:
    app: payment-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service-app
  template:
    metadata:
      labels:
        app: payment-service-app
    spec:
      containers:
      - name: payment-service-app
        image: djff94/payment-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
          - containerPort: 9696
        env:
          - name: SPRING_DATASOURCE_PASSWORD
            value: root
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://account-service-mysql-db:3306/testdb?createDatabaseIfNotExist=true&useSSL=false
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_JPA_HIBERNATE_DDL-AUTO
            value: update
          - name: EUREKA_URI
            value: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
          - name: S2S_LOCAL_TOKEN
            value: YXBpLXNlcnZpY2UtYWNjb3VudDpwd2QkMjAyMQ==
---

apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
spec:
  selector:
    app: payment-service-app
  ports:
  - port: 80
    targetPort: 9696

