spring:
    application:
        name: GATEWAY-SERVICE
    cloud:
        gateway:
            routes:
                - id: ORDER-SERVICE
                  uri: lb://ORDER-SERVICE
                  predicates:
                      - Path=/api/orders/**
#                - id: auth-service
#                  uri: lb://AUTH-SERVICE
#                  predicates:
#                      - Path=/api/auth/**

#management:
#    endpoints:
#        web:
#            exposure:
#                include: "*"

# Discovery Server Access
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
    instance:
        preferIpAddress: true
        hostname: eureka-0

# HTTP Server
server:
    port: 9191
