spring:
    application:
        name: GATEWAY-SERVICE
    cloud:
        gateway:
            routes:
                - id: ORDER-SERVICE
                  uri: lb://ORDER-SERVICE
                  predicates:
                      - Path=/api/orders/**
                - id: ACCOUNT-SERVICE
                  uri: lb://ACCOUNT-SERVICE
                  predicates:
                      - Path=/api/account/**
#management:
#    endpoints:
#        web:
#            exposure:
#                include: "*"

# Discovery Server Access
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true

# HTTP Server
server:
    port: 9191
