spring:
    application:
        name: GATEWAY-SERVICE
#    cloud:
#        gateway:
#            routes:
#                - id: auth-service
#                  uri: lb://AUTH-SERVICE
#                  predicates:
#                      - Path=/api/auth/**

management:
    endpoints:
        web:
            exposure:
                include: "*"

# Discovery Server Access
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true

# HTTP Server
server:
    port: 8080
