# Spring properties
spring:
  application:
    name: ACCOUNT-SERVICE
  config:
    import: optional:configserver:http://localhost:9296

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

# HTTP Server
server:
  port: 8282
