# Spring properties
spring:
  application:
    name: ACCOUNT-SERVICE
  config:
    import: optional:configserver:http://localhost:9296

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
  instance:
    preferIpAddress: true
    hostname: eureka-0

# HTTP Server
server:
  port: 8282
