spring:
  application:
    name: bank-service
server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone=http://localhost:8761/eureka/eureka:
        instance:
          hostname=localhost:
