server:
  port: 9296
spring:
  application:
    name: CONG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/3d3n/test-config-server
          clone-on-start: true
  profiles:
    active: native

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true